## 数据下载

https://grouplens.org/datasets/movielens/latest/

In [6]:
import pandas as pd
import numpy as np

In [10]:
dtype = {"userId" : np.int32, "movieId" : np.int32, "rating" : np.float32}
ratings = pd.read_csv("ml-latest-small/ratings.csv", dtype=dtype, usecols=range(3))

In [17]:
# 构建透视表，找到用户和电影之间的评分关系
ratings_matrix = ratings.pivot_table(index=['userId'], columns=['movieId'], values=['rating'])
ratings_matrix

        rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10
userId
1          4.0    NaN    4.0    NaN    NaN    4.0    NaN    NaN    NaN    NaN
2          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4          NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
5          4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606        2.5    NaN    NaN    NaN    NaN    NaN    2.5    NaN    NaN    NaN
607        4.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
608        2.5    2.0    2.0    NaN    NaN    NaN    NaN    NaN    NaN    4.0
609        3.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    4.0
610        5.0    NaN    NaN    NaN    NaN    5.0    NaN    NaN    NaN    NaN

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587
userId   ...
1        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
5        ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
607      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
608      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
609      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
610      ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN


movieId 193609
userId
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
...        ...
606        NaN
607        NaN
608        NaN
609        NaN
610        NaN

[610 rows x 9724 columns]